/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lavarapido.view;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import lavarapido.controller.TipoServicoController;
import lavarapido.model.TipoServico;

/**
 *
 * @author gabri
 */
public class TelaServicos extends javax.swing.JPanel {
    private DefaultTableModel modelo;
    private List<TipoServico> listaServicos;
    private final TipoServicoController servicoController = new TipoServicoController();

    /**
     * Creates new form TelaServicos
     * @throws java.sql.SQLException
     */
    public TelaServicos() throws SQLException {
        initComponents();
        configurarTabela();
        atualizarTabela();
        adicionarListenerDeEdicao();
    }
    
    private void configurarTabela() {
        modelo = new DefaultTableModel(
            new String[] {"ID", "Nome", "Preço", "Descrição"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return (column != 0 && column != 1); // ID não é editável
            }
        };

        tabelaServicos.setModel(modelo);
    }
    
    private void adicionarListenerDeEdicao() {
        modelo.addTableModelListener(e -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                int linha = e.getFirstRow();

                // Recupera os valores editados
                int id = (int) modelo.getValueAt(linha, 0);
                String precoStr = modelo.getValueAt(linha, 2).toString();
                String descricao = (String) modelo.getValueAt(linha, 3);
                
                Double preco;
                try {
                    preco = Double.parseDouble(precoStr);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "O preço deve ser um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                try {
                    servicoController.editarTipoServico(id, preco, descricao);
                    System.out.println("Serviço atualizado com sucesso.");
                    JOptionPane.showMessageDialog(null, "Serviço atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao atualizar serviço: " + ex.getMessage());
                }
            }
        });
    }
    
    private void atualizarTabela() throws SQLException {
        this.listaServicos = servicoController.listarTiposServico();

        modelo.setRowCount(0); // Limpa a tabela

        for (TipoServico servico : listaServicos) {
            modelo.addRow(new Object[] {
                servico.getId(),
                servico.getNome(),
                servico.getPreco(),
                servico.getDescricao(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TabelaClientePane = new javax.swing.JPanel();
        CadastrarClientTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        excluirBtn = new javax.swing.JButton();
        atualizarBtn = new javax.swing.JButton();
        CadastrarClientePane = new javax.swing.JPanel();
        CadastrarClientTitle = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        Inputs = new javax.swing.JPanel();
        TelefonePane = new javax.swing.JPanel();
        NomePane = new javax.swing.JPanel();
        NomeInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailPane = new javax.swing.JPanel();
        PrecoInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        criarClienteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescricaoInput = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        CadastrarClientTitle1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CadastrarClientTitle1.setText("Todos os serviços");

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaServicos);

        excluirBtn.setText("Excluir");
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });

        atualizarBtn.setText("Atualizar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabelaClientePaneLayout = new javax.swing.GroupLayout(TabelaClientePane);
        TabelaClientePane.setLayout(TabelaClientePaneLayout);
        TabelaClientePaneLayout.setHorizontalGroup(
            TabelaClientePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaClientePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TabelaClientePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabelaClientePaneLayout.createSequentialGroup()
                        .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(excluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CadastrarClientTitle1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        TabelaClientePaneLayout.setVerticalGroup(
            TabelaClientePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaClientePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CadastrarClientTitle1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(TabelaClientePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirBtn)
                    .addComponent(atualizarBtn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tabela", TabelaClientePane);

        CadastrarClientTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CadastrarClientTitle.setText("Cadastrar Serviço");

        javax.swing.GroupLayout TelefonePaneLayout = new javax.swing.GroupLayout(TelefonePane);
        TelefonePane.setLayout(TelefonePaneLayout);
        TelefonePaneLayout.setHorizontalGroup(
            TelefonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        TelefonePaneLayout.setVerticalGroup(
            TelefonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        jLabel3.setText("Nome");

        javax.swing.GroupLayout NomePaneLayout = new javax.swing.GroupLayout(NomePane);
        NomePane.setLayout(NomePaneLayout);
        NomePaneLayout.setHorizontalGroup(
            NomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NomePaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(NomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NomePaneLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addComponent(NomeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
        );
        NomePaneLayout.setVerticalGroup(
            NomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NomePaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLabel5.setText("Preço");

        javax.swing.GroupLayout EmailPaneLayout = new javax.swing.GroupLayout(EmailPane);
        EmailPane.setLayout(EmailPaneLayout);
        EmailPaneLayout.setHorizontalGroup(
            EmailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrecoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(EmailPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5))
        );
        EmailPaneLayout.setVerticalGroup(
            EmailPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmailPaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(PrecoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        criarClienteBtn.setText("Cadastrar");
        criarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarClienteBtnActionPerformed(evt);
            }
        });

        DescricaoInput.setColumns(20);
        DescricaoInput.setRows(5);
        jScrollPane2.setViewportView(DescricaoInput);

        jLabel6.setText("Descrição");

        javax.swing.GroupLayout InputsLayout = new javax.swing.GroupLayout(Inputs);
        Inputs.setLayout(InputsLayout);
        InputsLayout.setHorizontalGroup(
            InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputsLayout.createSequentialGroup()
                        .addGroup(InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InputsLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(418, 418, 418))
                            .addGroup(InputsLayout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(56, 56, 56)))
                        .addComponent(TelefonePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputsLayout.createSequentialGroup()
                        .addComponent(NomePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmailPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(criarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputsLayout.setVerticalGroup(
            InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelefonePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(criarClienteBtn)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CadastrarClientePaneLayout = new javax.swing.GroupLayout(CadastrarClientePane);
        CadastrarClientePane.setLayout(CadastrarClientePaneLayout);
        CadastrarClientePaneLayout.setHorizontalGroup(
            CadastrarClientePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator)
            .addComponent(Inputs, javax.swing.GroupLayout.PREFERRED_SIZE, 732, Short.MAX_VALUE)
            .addGroup(CadastrarClientePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CadastrarClientTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CadastrarClientePaneLayout.setVerticalGroup(
            CadastrarClientePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarClientePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CadastrarClientTitle)
                .addGap(20, 20, 20)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Cadastrar", CadastrarClientePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        int linhaSelecionada = tabelaServicos.getSelectedRow();
        if (linhaSelecionada != -1) {
            int id = (int) tabelaServicos.getValueAt(linhaSelecionada, 0);
            String nome = (String) tabelaServicos.getValueAt(linhaSelecionada, 1); // nome está na coluna 1

            int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir o serviço \"" + nome + "\"?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
            );

            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    servicoController.excluirTipoServico(id);
                    atualizarTabela(); // para atualizar a exibição da tabela
                } catch (SQLException ex) {
                    Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Erro ao excluir serviço: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um serviço para excluir.");
        }
    }//GEN-LAST:event_excluirBtnActionPerformed

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        try {
            atualizarTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizarBtnActionPerformed

    private void criarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarClienteBtnActionPerformed
        String Nome = NomeInput.getText().trim();
        String Preco = PrecoInput.getText().trim();
        String Descricao = DescricaoInput.getText().trim();
                

        // Verificações básicas
        if (Nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O nome é obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Preco.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O preço é obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double precoConvertido;
        try {
            precoConvertido = Double.parseDouble(Preco);
            // Se quiser usar o valor convertido depois, use a variável precoConvertido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O preço deve ser um número válido (use ponto, não vírgula).", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Descricao.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A descrição é obrigatória.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            TipoServico novoServico = new TipoServico(0, Nome, Descricao, precoConvertido);
            servicoController.cadastrarTipoServico(novoServico);
            JOptionPane.showMessageDialog(null, "Serviço criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            atualizarTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_criarClienteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarClientTitle;
    private javax.swing.JLabel CadastrarClientTitle1;
    private javax.swing.JPanel CadastrarClientePane;
    private javax.swing.JTextArea DescricaoInput;
    private javax.swing.JPanel EmailPane;
    private javax.swing.JPanel Inputs;
    private javax.swing.JTextField NomeInput;
    private javax.swing.JPanel NomePane;
    private javax.swing.JTextField PrecoInput;
    private javax.swing.JSeparator Separator;
    private javax.swing.JPanel TabelaClientePane;
    private javax.swing.JPanel TelefonePane;
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JButton criarClienteBtn;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaServicos;
    // End of variables declaration//GEN-END:variables
}
